# theme: jekyll-theme-slate

remote_theme: just-the-docs/just-the-docs

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
heading_level: 6

# Maximum amount of previews per search result
# Default: 3
previews: 5

# Maximum amount of words to display before a matched word in the preview
# Default: 5
preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
preview_words_after: 10

# Set the search token separator
# Default: /[\s\-/]+/
# Example: enable support for hyphenated search words
tokenizer_separator: /[\s/]+/

# Display the relative url in search results
# Supports true (default) or false
rel_url: true

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
button: true

heading_anchors: true

footer_content: "The content in this site is covered by the RESO EULA. <a href=\"https://www.reso.org/eula/\">READ MORE</a>"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."


# TODO logo: ""
